import { CommonModule } from '@angular/common';
import { Component } from '@angular/core';

import { IonRouterOutlet, IonApp } from '@ionic/angular/standalone';
import { addIcons } from 'ionicons';
import {
  homeSharp,
  homeOutline,
  cubeSharp,
  cubeOutline,
  arrowUpSharp,
  arrowUpOutline,
  arrowDownSharp,
  arrowDownOutline,
  arrowUndoSharp,
  arrowUndoOutline,
  arrowBackSharp,
  arrowBackOutline,
  pencilSharp,
  pencilOutline,
  menuSharp,
  menuOutline,
  bookSharp,
  bookOutline,
  gridSharp,
  gridOutline,
  peopleSharp,
  peopleOutline,
  receiptSharp,
  receiptOutline,
  addSharp,
  addOutline,
  closeSharp,
  closeOutline,
  checkmarkSharp,
  checkmarkOutline,
  listSharp,
  listOutline,
  trashSharp,
  trashOutline,
  leafSharp,
  leafOutline,
  addCircleOutline,
  addCircleSharp,
  informationCircleOutline,
  informationCircleSharp,
  arrowForwardCircleOutline,
  arrowForwardCircleSharp,
  calculatorOutline,
  calculatorSharp,
} from 'ionicons/icons';

@Component({
  selector: 'app-root',
  templateUrl: 'app.component.html',
  standalone: true,
  imports: [
    CommonModule,
    IonRouterOutlet,
    IonApp
  ],
})
export class AppComponent {

  isIframe = window !== window.parent && !window.opener;
    constructor() {
    addIcons({
      homeSharp,
      homeOutline,
      cubeSharp,
      cubeOutline,
      arrowUpSharp,
      arrowUpOutline,
      arrowDownSharp,
      arrowDownOutline,
      arrowUndoSharp,
      arrowUndoOutline,
      menuSharp,
      menuOutline,
      bookSharp,
      bookOutline,
      gridSharp,
      gridOutline,
      peopleSharp,
      peopleOutline,
      receiptSharp,
      receiptOutline,
      addSharp,
      addOutline,
      closeSharp,
      closeOutline,
      checkmarkSharp,
      checkmarkOutline,
      arrowBackSharp,
      arrowBackOutline,
      pencilSharp,
      pencilOutline,
      listSharp,
      listOutline,
      trashSharp,
      trashOutline,
      leafSharp,
      leafOutline,
      addCircleOutline,
      addCircleSharp,
      informationCircleOutline,
      informationCircleSharp,
      arrowForwardCircleOutline,
      arrowForwardCircleSharp,
      calculatorOutline,
      calculatorSharp
    });
  }
}
